Updated compile.md
Distorm moved to git.
Libdwarf instructions referenced wrong version file in some locations.
The progress command was not found, so I just removed it.

Added a sudo make install to the llvm release build step.

Getting error
ERROR: glib-2.22 gthread-2.0 is required to compile QEMU
build-dep qemu could not be found .. so maybe that was why?

And then something like this.
sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.

:(